### ISSUE TITLE
compile  v4.16.13-galliumos keyboard

### ISSUE THREAD

**Issue by kristoferus75** [GalliumOS/linux#1]
Hi !

I have compiled the v4.16.13-galliumos version for my chromebook but the keyboard doesn't  work  !
with the compiled v4.15.18 ist works without a problem ?

Please help !

kind regards 

kristoferus75

**Comment by reynhout** [comment]
@kristoferus75 This kernel hasn't been tested. It's marked `dev`, and not available in our APT repos. So it's not surprising that it doesn't work everywhere.

That said, we appreciate the help testing it. We'll need your Chromebook model, and which firmware you are running, to be able to log your report though.

Thanks!

PS: I'll be closing this ticket and disabling issues on this GitHub repo. We track all issues on the main tracker at https://github.com/galliumos/galliumos-distro/issues.

**Comment by reynhout** [comment]
@kristoferus75 This kernel hasn't been tested yet. It's marked `dev`, and is not available in our APT repos -- so you should expect some hiccups.

That said, we appreciate your help testing. We'll need your Chromebook model, and which firmware you are running, to be able to log your report though.

Please also include the full set of steps you used to build and install it, since your process might differ.

Thanks!

**Comment by reynhout** [comment]
OK, we'll be sure to test on EDGAR, thanks. I've tested on two Braswells (TERRA, CYAN) which should be very similar if not identical -- all looks good in my testing.

I'm closing this ticket (and tracker). We use https://github.com/galliumos/galliumos-distro for all GalliumOS issue tracking. If you have non-GalliumOS questions, please try IRC or Reddit. Thanks.
